#RAILS_ENV=production
User.create(name: "gonza", email: "ka.baseball1997@gmail.com", password: "666666")



Top.create(maintitle: "this is top")

Mainpart.create(mp_name: "外壁",top_id: 1)
Mainpart.create(mp_name: "内壁",top_id: 1)
Mainpart.create(mp_name: "屋根",top_id: 1)

Material.create(mate_name: "塗装" ,mainpart_id: 1,top_id: 1)
Material.create(mate_name: "タイル",mainpart_id: 1,top_id: 1)
Material.create(mate_name: "パネル",mainpart_id: 1,top_id: 1)

Material.create(mate_name: "塗装" ,mainpart_id: 11,top_id: 1)
Material.create(mate_name: "タイル",mainpart_id: 11,top_id: 1)
Material.create(mate_name: "パネル",mainpart_id: 11,top_id: 1)

Material.create(mate_name: "塗装" ,mainpart_id: 21,top_id: 1)
Material.create(mate_name: "タイル",mainpart_id: 21,top_id: 1)
Material.create(mate_name: "パネル",mainpart_id: 21,top_id: 1)

Symptom.create(s_name: "ひび割れ(塗装)", material_id: 1, mainpart_id: 1,top_id: 1)
Symptom.create(s_name: "剥がれ(塗装)", material_id: 1, mainpart_id: 1,top_id: 1)
Symptom.create(s_name: "色褪せ(塗装)", material_id: 1, mainpart_id: 1,top_id: 1)
Symptom.create(s_name: "ひび割れ(タイル)", material_id: 11, mainpart_id: 1,top_id: 1)
Symptom.create(s_name: "剥がれ(タイル)", material_id: 11, mainpart_id: 1,top_id: 1)
Symptom.create(s_name: "色褪せ(タイル)", material_id: 11, mainpart_id: 1,top_id: 1)
Symptom.create(s_name: "ひび割れ(パネル)", material_id: 21, mainpart_id: 1,top_id: 1)
Symptom.create(s_name: "剥がれ(パネル)", material_id: 21, mainpart_id: 1,top_id: 1)
Symptom.create(s_name: "色褪せ(パネル)", material_id: 21, mainpart_id: 1,top_id: 1)

Symptom.create(s_name: "ひび割れ(塗装)", material_id: 31, mainpart_id: 11,top_id: 1)
Symptom.create(s_name: "剥がれ(塗装)", material_id: 31, mainpart_id: 11,top_id: 1)
Symptom.create(s_name: "色褪せ(塗装)", material_id: 31, mainpart_id: 11,top_id: 1)
Symptom.create(s_name: "ひび割れ(タイル)", material_id: 41, mainpart_id: 11,top_id: 1)
Symptom.create(s_name: "剥がれ(タイル)", material_id: 41, mainpart_id: 11,top_id: 1)
Symptom.create(s_name: "色褪せ(タイル)", material_id: 41, mainpart_id: 11,top_id: 1)
Symptom.create(s_name: "ひび割れ(パネル)", material_id: 51, mainpart_id: 11,top_id: 1)
Symptom.create(s_name: "剥がれ(パネル)", material_id: 51, mainpart_id: 11,top_id: 1)
Symptom.create(s_name: "色褪せ(パネル)", material_id: 51, mainpart_id: 11,top_id: 1)

Symptom.create(s_name: "ひび割れ(塗装)", material_id: 61, mainpart_id: 21,top_id: 1)
Symptom.create(s_name: "剥がれ(塗装)", material_id: 61, mainpart_id: 21,top_id: 1)
Symptom.create(s_name: "色褪せ(塗装)", material_id: 61, mainpart_id: 21,top_id: 1)
Symptom.create(s_name: "ひび割れ(タイル)", material_id: 71, mainpart_id: 21,top_id: 1)
Symptom.create(s_name: "剥がれ(タイル)", material_id: 71, mainpart_id: 21,top_id: 1)
Symptom.create(s_name: "色褪せ(タイル)", material_id: 71, mainpart_id: 21,top_id: 1)
Symptom.create(s_name: "ひび割れ(パネル)", material_id: 81, mainpart_id: 21,top_id: 1)
Symptom.create(s_name: "剥がれ(パネル)", material_id: 81, mainpart_id: 21,top_id: 1)
Symptom.create(s_name: "色褪せ(パネル)", material_id: 81, mainpart_id: 21,top_id: 1)

Detail.create(detail_name: "ひび割れ(塗装)①",condition: "ひどいひび割れ①です",treatment: "ひび①修理します", mainpart_id: 1, material_id: 1, symptom_id: 1 ,detail_type: "壁",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)②",condition: "ひどいひび割れ②です2",treatment: "ひび②修理します2", mainpart_id: 1, material_id: 1, symptom_id: 1 ,detail_type: "壁",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)③",condition: "ひどいひび割れ③です3",treatment: "ひび③修理します3", mainpart_id: 1, material_id: 1, symptom_id: 1 ,detail_type: "壁",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)①",condition: "ひどいひび割れ①です",treatment: "ひび①修理します", mainpart_id: 1, material_id: 1, symptom_id: 11 ,detail_type: "壁",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)②",condition: "ひどいひび割れ②です2",treatment: "ひび②修理します2", mainpart_id: 1, material_id: 1, symptom_id: 11 ,detail_type: "壁",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)③",condition: "ひどいひび割れ③です3",treatment: "ひび③修理します3", mainpart_id: 1, material_id: 1, symptom_id: 11 ,detail_type: "壁",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)①",condition: "ひどいひび割れ①です",treatment: "ひび①修理します", mainpart_id: 1, material_id: 1, symptom_id: 21 ,detail_type: "壁",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)②",condition: "ひどいひび割れ②です2",treatment: "ひび②修理します2", mainpart_id: 1, material_id: 1, symptom_id: 21 ,detail_type: "壁",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)③",condition: "ひどいひび割れ③です3",treatment: "ひび③修理します3", mainpart_id: 1, material_id: 1, symptom_id: 21 ,detail_type: "壁",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)①",condition: "ひどいひび割れ①です",treatment: "ひび①修理します", mainpart_id: 1, material_id: 11, symptom_id: 31 ,detail_type: "壁",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)②",condition: "ひどいひび割れ②です2",treatment: "ひび②修理します2", mainpart_id: 1, material_id: 11, symptom_id: 31 ,detail_type: "壁",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)③",condition: "ひどいひび割れ③です3",treatment: "ひび③修理します3", mainpart_id: 1, material_id: 11, symptom_id: 31 ,detail_type: "壁",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)①",condition: "ひどいひび割れ①です",treatment: "ひび①修理します", mainpart_id: 1, material_id: 11, symptom_id: 41 ,detail_type: "壁",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)②",condition: "ひどいひび割れ②です2",treatment: "ひび②修理します2", mainpart_id: 1, material_id: 11, symptom_id: 41 ,detail_type: "壁",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)③",condition: "ひどいひび割れ③です3",treatment: "ひび③修理します3", mainpart_id: 1, material_id: 11, symptom_id: 41 ,detail_type: "壁",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)①",condition: "ひどいひび割れ①です",treatment: "ひび①修理します", mainpart_id: 1, material_id: 11, symptom_id: 51 ,detail_type: "壁",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)②",condition: "ひどいひび割れ②です2",treatment: "ひび②修理します2", mainpart_id: 1, material_id: 11, symptom_id: 51 ,detail_type: "壁",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)③",condition: "ひどいひび割れ③です3",treatment: "ひび③修理します3", mainpart_id: 1, material_id: 11, symptom_id: 51 ,detail_type: "壁",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)①",condition: "ひどいひび割れ①です",treatment: "ひび①修理します", mainpart_id: 1, material_id: 21, symptom_id: 61 ,detail_type: "壁",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)②",condition: "ひどいひび割れ②です2",treatment: "ひび②修理します2", mainpart_id: 1, material_id: 21, symptom_id: 61 ,detail_type: "壁",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)③",condition: "ひどいひび割れ③です3",treatment: "ひび③修理します3", mainpart_id: 1, material_id: 21, symptom_id: 61 ,detail_type: "壁",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)①",condition: "ひどいひび割れ①です",treatment: "ひび①修理します", mainpart_id: 1, material_id: 21, symptom_id: 71 ,detail_type: "壁",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)②",condition: "ひどいひび割れ②です2",treatment: "ひび②修理します2", mainpart_id: 1, material_id: 21, symptom_id: 71 ,detail_type: "壁",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)③",condition: "ひどいひび割れ③です3",treatment: "ひび③修理します3", mainpart_id: 1, material_id: 21, symptom_id: 71 ,detail_type: "壁",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)①",condition: "ひどいひび割れ①です",treatment: "ひび①修理します", mainpart_id: 1, material_id: 21, symptom_id: 81 ,detail_type: "壁",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)②",condition: "ひどいひび割れ②です2",treatment: "ひび②修理します2", mainpart_id: 1, material_id: 21, symptom_id: 81 ,detail_type: "壁",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)③",condition: "ひどいひび割れ③です3",treatment: "ひび③修理します3", mainpart_id: 1, material_id: 21, symptom_id: 81 ,detail_type: "壁",top_id: 1)

Detail.create(detail_name: "ひび割れ(塗装)①",condition: "ひどいひび割れ①です",treatment: "ひび①修理します", mainpart_id: 11, material_id: 31, symptom_id: 91 ,detail_type: "壁2",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)②",condition: "ひどいひび割れ②です2",treatment: "ひび②修理します2", mainpart_id: 11, material_id: 31, symptom_id: 91 ,detail_type: "壁2",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)③",condition: "ひどいひび割れ③です3",treatment: "ひび③修理します3", mainpart_id: 11, material_id: 31, symptom_id: 91 ,detail_type: "壁2",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)①",condition: "ひどいひび割れ①です",treatment: "ひび①修理します", mainpart_id: 11, material_id: 31, symptom_id: 101 ,detail_type: "壁2",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)②",condition: "ひどいひび割れ②です2",treatment: "ひび②修理します2", mainpart_id: 11, material_id: 31, symptom_id: 101 ,detail_type: "壁2",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)③",condition: "ひどいひび割れ③です3",treatment: "ひび③修理します3", mainpart_id: 11, material_id: 31, symptom_id: 101 ,detail_type: "壁2",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)①",condition: "ひどいひび割れ①です",treatment: "ひび①修理します", mainpart_id: 11, material_id: 31, symptom_id: 111 ,detail_type: "壁2",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)②",condition: "ひどいひび割れ②です2",treatment: "ひび②修理します2", mainpart_id: 11, material_id: 31, symptom_id: 111 ,detail_type: "壁2",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)③",condition: "ひどいひび割れ③です3",treatment: "ひび③修理します3", mainpart_id: 11, material_id: 31, symptom_id: 111 ,detail_type: "壁2",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)①",condition: "ひどいひび割れ①です",treatment: "ひび①修理します", mainpart_id: 11, material_id: 41, symptom_id: 121 ,detail_type: "壁2",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)②",condition: "ひどいひび割れ②です2",treatment: "ひび②修理します2", mainpart_id: 11, material_id: 41, symptom_id: 121 ,detail_type: "壁2",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)③",condition: "ひどいひび割れ③です3",treatment: "ひび③修理します3", mainpart_id: 11, material_id: 41, symptom_id: 121 ,detail_type: "壁2",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)①",condition: "ひどいひび割れ①です",treatment: "ひび①修理します", mainpart_id: 11, material_id: 41, symptom_id: 131 ,detail_type: "壁2",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)②",condition: "ひどいひび割れ②です2",treatment: "ひび②修理します2", mainpart_id: 11, material_id: 41, symptom_id: 131 ,detail_type: "壁2",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)③",condition: "ひどいひび割れ③です3",treatment: "ひび③修理します3", mainpart_id: 11, material_id: 41, symptom_id: 131 ,detail_type: "壁2",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)①",condition: "ひどいひび割れ①です",treatment: "ひび①修理します", mainpart_id: 11, material_id: 41, symptom_id: 141 ,detail_type: "壁2",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)②",condition: "ひどいひび割れ②です2",treatment: "ひび②修理します2", mainpart_id: 11, material_id: 41, symptom_id: 141 ,detail_type: "壁2",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)③",condition: "ひどいひび割れ③です3",treatment: "ひび③修理します3", mainpart_id: 11, material_id: 41, symptom_id: 141 ,detail_type: "壁2",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)①",condition: "ひどいひび割れ①です",treatment: "ひび①修理します", mainpart_id: 11, material_id: 51, symptom_id: 151 ,detail_type: "壁2",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)②",condition: "ひどいひび割れ②です2",treatment: "ひび②修理します2", mainpart_id: 11, material_id: 51, symptom_id: 151 ,detail_type: "壁2",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)③",condition: "ひどいひび割れ③です3",treatment: "ひび③修理します3", mainpart_id: 11, material_id: 51, symptom_id: 151 ,detail_type: "壁2",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)①",condition: "ひどいひび割れ①です",treatment: "ひび①修理します", mainpart_id: 11, material_id: 51, symptom_id: 161 ,detail_type: "壁2",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)②",condition: "ひどいひび割れ②です2",treatment: "ひび②修理します2", mainpart_id: 11, material_id: 51, symptom_id: 161 ,detail_type: "壁2",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)③",condition: "ひどいひび割れ③です3",treatment: "ひび③修理します3", mainpart_id: 11, material_id: 51, symptom_id: 161 ,detail_type: "壁2",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)①",condition: "ひどいひび割れ①です",treatment: "ひび①修理します", mainpart_id: 11, material_id: 51, symptom_id: 171 ,detail_type: "壁2",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)②",condition: "ひどいひび割れ②です2",treatment: "ひび②修理します2", mainpart_id: 11, material_id: 51, symptom_id: 171 ,detail_type: "壁2",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)③",condition: "ひどいひび割れ③です3",treatment: "ひび③修理します3", mainpart_id: 11, material_id: 51, symptom_id: 171 ,detail_type: "壁2",top_id: 1)

Detail.create(detail_name: "ひび割れ(塗装)①",condition: "ひどいひび割れ①です",treatment: "ひび①修理します", mainpart_id: 21, material_id: 61, symptom_id: 181 ,detail_type: "壁3",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)②",condition: "ひどいひび割れ②です2",treatment: "ひび②修理します2", mainpart_id: 21, material_id: 61, symptom_id: 181 ,detail_type: "壁3",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)③",condition: "ひどいひび割れ③です3",treatment: "ひび③修理します3", mainpart_id: 21, material_id: 61, symptom_id: 181 ,detail_type: "壁3",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)①",condition: "ひどいひび割れ①です",treatment: "ひび①修理します", mainpart_id: 21, material_id: 61, symptom_id: 191 ,detail_type: "壁3",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)②",condition: "ひどいひび割れ②です2",treatment: "ひび②修理します2", mainpart_id: 21, material_id: 61, symptom_id: 191 ,detail_type: "壁3",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)③",condition: "ひどいひび割れ③です3",treatment: "ひび③修理します3", mainpart_id: 21, material_id: 61, symptom_id: 191 ,detail_type: "壁3",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)①",condition: "ひどいひび割れ①です",treatment: "ひび①修理します", mainpart_id: 21, material_id: 61, symptom_id: 201 ,detail_type: "壁3",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)②",condition: "ひどいひび割れ②です2",treatment: "ひび②修理します2", mainpart_id: 21, material_id: 61, symptom_id: 201 ,detail_type: "壁3",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)③",condition: "ひどいひび割れ③です3",treatment: "ひび③修理します3", mainpart_id: 21, material_id: 61, symptom_id: 201 ,detail_type: "壁3",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)①",condition: "ひどいひび割れ①です",treatment: "ひび①修理します", mainpart_id: 21, material_id: 71, symptom_id: 211 ,detail_type: "壁3",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)②",condition: "ひどいひび割れ②です2",treatment: "ひび②修理します2", mainpart_id: 21, material_id: 71, symptom_id: 211 ,detail_type: "壁3",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)③",condition: "ひどいひび割れ③です3",treatment: "ひび③修理します3", mainpart_id: 21, material_id: 71, symptom_id: 211 ,detail_type: "壁3",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)①",condition: "ひどいひび割れ①です",treatment: "ひび①修理します", mainpart_id: 21, material_id: 71, symptom_id: 221 ,detail_type: "壁3",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)②",condition: "ひどいひび割れ②です2",treatment: "ひび②修理します2", mainpart_id: 21, material_id: 71, symptom_id: 221 ,detail_type: "壁3",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)③",condition: "ひどいひび割れ③です3",treatment: "ひび③修理します3", mainpart_id: 21, material_id: 71, symptom_id: 221 ,detail_type: "壁3",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)①",condition: "ひどいひび割れ①です",treatment: "ひび①修理します", mainpart_id: 21, material_id: 71, symptom_id: 231 ,detail_type: "壁3",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)②",condition: "ひどいひび割れ②です2",treatment: "ひび②修理します2", mainpart_id: 21, material_id: 71, symptom_id: 231 ,detail_type: "壁3",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)③",condition: "ひどいひび割れ③です3",treatment: "ひび③修理します3", mainpart_id: 21, material_id: 71, symptom_id: 231 ,detail_type: "壁3",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)①",condition: "ひどいひび割れ①です",treatment: "ひび①修理します", mainpart_id: 21, material_id: 81, symptom_id: 241 ,detail_type: "壁3",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)②",condition: "ひどいひび割れ②です2",treatment: "ひび②修理します2", mainpart_id: 21, material_id: 81, symptom_id: 241 ,detail_type: "壁3",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)③",condition: "ひどいひび割れ③です3",treatment: "ひび③修理します3", mainpart_id: 21, material_id: 81, symptom_id: 241 ,detail_type: "壁3",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)①",condition: "ひどいひび割れ①です",treatment: "ひび①修理します", mainpart_id: 21, material_id: 81, symptom_id: 251 ,detail_type: "壁3",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)②",condition: "ひどいひび割れ②です2",treatment: "ひび②修理します2", mainpart_id: 21, material_id: 81, symptom_id: 251 ,detail_type: "壁3",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)③",condition: "ひどいひび割れ③です3",treatment: "ひび③修理します3", mainpart_id: 21, material_id: 81, symptom_id: 251 ,detail_type: "壁3",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)①",condition: "ひどいひび割れ①です",treatment: "ひび①修理します", mainpart_id: 21, material_id: 81, symptom_id: 261 ,detail_type: "壁3",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)②",condition: "ひどいひび割れ②です2",treatment: "ひび②修理します2", mainpart_id: 21, material_id: 81, symptom_id: 261 ,detail_type: "壁3",top_id: 1)
Detail.create(detail_name: "ひび割れ(塗装)③",condition: "ひどいひび割れ③です3",treatment: "ひび③修理します3", mainpart_id: 21, material_id: 81, symptom_id: 261 ,detail_type: "壁3",top_id: 1)
